# The book's title. Will be used everywhere!
title: "Operations Playbook"

# The book's language.
language: en

# Your book copyright info.
copyright: "Copyright (C) 2025 Solo Aviation Services, LLC. All rights reserved."

# Who's publishing this book.
publisher: "Solo Aviation Services"

# When this book was published.
published_at: "2025-08-21"

# Some book description.
subject: "Operations Playbook"

# Some keywords that identify this book.
keywords: "FBO, aviation, operations, procedures, aircraft, maintenance, safety, compliance"

# Some unique identification. Works great with your domain
uid: "solo-aviation-services-playbook-2025"

# Your book identification like ISBN or ISSN.
identifier:
  id: "solo-aviation-services-playbook"
  type: "URL"

# This book authors.
authors:
  - "Solo Aviation Services, LLC"

# Syntax highlight theme. Can be any of supported by Rouge.
# theme: github
theme: monokai

# Output directory - keeping default for now
# Custom copying handled in build script
